#服务器配置
# security.user.name = adolfo
# security.user.password = 123
server:
  #端口
  port: 10000
#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: jjfwpt-auth-gateway
zuul:
  #路由配置
  routes:
    kibana:
      id: kibana
      path: /kibana/**
      url: http://114.116.117.206:5601
#    auth:    #认证服务
#      #响应的路径
#      path: /auth/**
#      #敏感头信息
#      sensitiveHeaders:
#      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
#      serviceId:  jjfwpt-auth-service
    jjfwpt-sys-service: #生产者服务
      #响应的路径
      path: /sys/**
      #敏感头信息
      sensitiveHeaders:
      service-id: jjfwpt-sys-service
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
  #添加代理头
  add-proxy-headers: true
  retryable: true


hystrix:
  metrics:
    polling-interval-ms: 1000
