server:
  port: 20001
spring:
  application:
    name: jjfwpt-biz-service
  datasource:
    druid:
      url: jdbc:mysql://114.116.117.206:3306/iwant?useUnicode=true&characterEncoding=utf8
      username: root
      password: WANGJUN1Q2W3E13
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1
